### PR TITLE
force `emitDeclarationOnly: false`

### LINKED ISSUE #32: ts2gas fails with message `Debug Failure. Output generation failed`
If the compilerOptions `emitDeclarationOnly` is passed with the value `true` (typically by clasp reading the tsconfig.json) then ts2gas fails with message `Debug Failure. Output generation failed`

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
This fixes #32 

No test case added but verified with a clasp project by adding `emitDeclarationOnly: true` to the compile options

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -169,6 +169,7 @@ const ts2gas = (source: string, transpileOptions: ts.TranspileOptions = {}) => {
   /** These the settings are always used */
   const statics: ts.TranspileOptions = {
     compilerOptions: {
+      emitDeclarationOnly: false,
```
Comment (grant) [inline src/index.ts]: Add a comment. Change to:
```ts
emitDeclarationOnly: false, // explicitly force transpiled files.
```
